version: 2.1

jobs:
  run-tests:
    machine:
      image: ubuntu-2004:202101-01
    working_directory: ~/repo
    steps:
      - checkout
      # Download and cache dependencies
      - restore_cache:
          keys:
            - v1-dependencies-{{ checksum "requirements.txt" }}-{{ checksum "requirements_testing.txt" }}
            # fallback to using the latest cache if no exact match is found
            - v1-dependencies-

      - run:
          name: install dependencies
          command: |
            python3 --version
            python3 -m venv ~/venv
            source ~/venv/bin/activate
            pip3 install -r requirements.txt
            pip3 install -r requirements_testing.txt

      - save_cache:
          paths:
            - ~/venv
          key: v1-dependencies-{{ checksum "requirements.txt" }}-{{ checksum "requirements_testing.txt" }}

      - run:
          name: Run pytest
          command: |
            source ~/venv/bin/activate
            pytest gigantumcli/tests

workflows:
  version: 2
  run_tests:
    jobs:
      - run-tests
