version: 2.1

executors:
  cli-test:
    docker:
      - image: circleci/python:3.6.1

jobs:
  run-tests:
    executor: cli-test
    working_directory: ~/repo
    steps:
      - checkout
      - setup_remote_docker
      # Download and cache dependencies
      - restore_cache:
          keys:
            - v1-dependencies-{{ checksum "requirements.txt" }}
            # fallback to using the latest cache if no exact match is found
            - v1-dependencies-

      - run:
          name: install dependencies
          command: |
            python3 -m venv venv
            . venv/bin/activate
            pip install -r requirements.txt
            pip install -r requirements_testing.txt

      - save_cache:
          paths:
            - ./venv
          key: v1-dependencies-{{ checksum "requirements.txt" }}

      - run:
          name: Run pytest
          command: |
            . venv/bin/activate
            pytest gigantumcli/tests

workflows:
  version: 2
  run_tests:
    jobs:
      - run-tests
